<?php
  function uib_theme_hack_entity_view_alter(&$build, $type) {
    $server = 'http://uib.no/';
    if ($type == 'node') {
      $w2_path = $build['field_uib_w2_path'][0]['#markup'];
      $build['field_uib_w2_path'][0]['#markup'] = '<a href="'  . $server . $w2_path . '">' . $w2_path . '</a>';
    }
    $w2_id =  $build['field_uib_w2_id'][0]['#markup'];
    $build['field_uib_w2_id'][0]['#markup'] = '<a href="' . $server . 'topicmap/@@xtopic?id=' . $w2_id . '">' . $w2_id . '</a>';
  }
