<?php
/**
 * @file
 * Code for the UIB webdesk feature.
 */

include_once 'uib_webdesk.features.inc';

/**
* Implements hook_admin_menu_output_alter
*/
function uib_webdesk_admin_menu_output_alter(&$content) {
  global $user;
  if ( (in_array('level 2', array_values($user->roles))) || (in_array('level 3', array_values($user->roles))) ) {
    // Do not let users at level 2 and level 3 see these admin menu items
    $content['menu']['admin/help']['#access'] = FALSE;
    $content['menu']['admin/index']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_alter
 */

function uib_webdesk_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "views_exposed_form"){
    $form['field_uib_event_type_value']['#states'] = array(
      'enabled' => array(
        ':input[name="field_uib_article_type_value"]' => array('value' => 'event'),
       ),
    );
  }
}
