<?php

/**
 * Implements hook_context_plugins().
 */
function uib_context_context_plugins() {
  $plugins = array();
  $plugins['uib_area'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'uib_context') . '/plugins',
      'file' => 'uib_context_condition_area.inc',
      'class' => 'uib_area',
      'parent' => 'context_condition',
    ),
  );

  $plugins['uib_area_reaction'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'uib_context') . '/plugins',
      'file' => 'uib_context_reaction_area.inc',
      'class' => 'uib_area_reaction',
      'parent' => 'context_reaction',
    ),
  );

  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function uib_context_context_registry() {
  $registry = array();
  $registry['conditions'] = array(
    'area' => array(
      'title' => t('UiB area'),
      'description' => t('Content type not to check.'),
      'plugin' => 'uib_area',
    ),
  );

  $registry['reactions'] = array(
    'areaid' => array(
      'title' => t('UiB area'),
      'plugin' => 'uib_area_reaction',
    ),
  );

  return $registry;
}

/**
 * Execute Context page reactions.
 *
 */
function uib_context_context_page_reaction() {
  if ($plugin = context_get_plugin('reaction', 'areaid')) {
    // $plugin->execute();
  }
}

/**
 * Implements hook_node_view()
 */
function uib_context_node_view($node, $view_mode, $langcode) {
  $contexts = context_active_contexts();

  if (isset($node->field_uib_area['und'][0]['target_id'])) {

    if ($plugin = context_get_plugin('reaction', 'areaid')) {
      $ref_nid = $node->field_uib_area['und'][0]['target_id'];
      $ref_title = $plugin->execute($ref_nid);
      dpm($ref_title, 'Node belong to');
    }
  }
}
