<?php

/**
* @file
* uib_setup.install
*
* Implements hook_install()
*/
function uib_setup_install() {
  foreach (array('d.m.y', 'd.m.Y', 'd.m.Y - H.s') as $format) {
    system_date_format_save(array(
      'type' => 'custom',
      'format' => $format,
      'locked' => 0,
      'is_new' => 1,
    ));
  }
}

/**
 * Enable new module: uib_urlfilter
 */
function uib_setup_update_7000() {
  module_enable(array('uib_urlfilter'));
}
