<?php
/**
 * @file
 * Code for the UiB Setup feature.
 */

include_once 'uib_setup.features.inc';

/**
 * Implements hook_menu_alter().
 */
function uib_setup_menu_alter(&$items) {
  // PI-884 Disable the "Request New Password" tab
  $items['user/password']['access callback'] = FALSE;
}

/**
 * Implements hook_block_view_MODULE_DELTA_alter().
 */
function uib_setup_block_view_locale_language_alter(&$data, $block) {
   unset($data['subject']);
}

/**
 * Implements hook_language_negotiation_info().
 */

function uib_setup_language_negotiation_info() {
  return array(
    'uib-rules' => array(
      'callbacks' => array(
        'language' => 'uib_setup__language_callback',
        'url_rewrite' => 'uib_setup__url_rewrite_callback',
      ),
      'file' => drupal_get_path('module', 'uib_setup') . '/uib_setup.module',
      'name' => t('UiB rules'),
      'description' => t('UiB custom rules for mapping URLs to language. Currently it just forces Norwegian and is expected to be enabled after URL prefix mapping.'),
      'cache' => 0,
    ),
  );
}

/**
 * Force Norwegian language for most URLs
 */
function uib_setup__language_callback($languages) {
  $lang = 'nb';
  if (isset($languages[$lang]->enabled) && $languages[$lang]->enabled) {
    return $lang;
  }
  return FALSE;
}

/**
 * Forcibly removing Norwegian language prefix in url
 */
function uib_setup__url_rewrite_callback (&$path, &$options) {
  if ($options['prefix'] == 'nb/') {
    $options['prefix'] = "";
  }
}

/**
* Implements hook_entity_info_alter().
* Custom view modes for files
*/
function uib_setup_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['full_width_image'] = array(
    'label' => t('Full width image (16:9)'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['wide_thumbnail'] = array(
    'label' => t('Wide thumbnail'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['area_bottom'] = array(
    'label' => t('Area bottom'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['content_sidebar'] = array(
    'label' => t('Content sidebar'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['content_main'] = array(
    'label' => t('Content main'),
    'custom settings' => TRUE,
  );
}

