<?php

/**
 * Alternative logger that will log stuff with drush_log() if running under
 * drush; otherwise redirect messages to the watchdog log.
 */

function uibx_log($message, $type='notice') {
  if (function_exists('drush_log')) {
    drush_log($message, $type);
  }
  else {
    switch ($type) {
    case 'error':
    case 'failed':
      $severity = WATCHDOG_ERROR;
      break;
    case 'warning':
      $severity = WATCHDOG_WARNING;
      break;
    default:
      $severity = WATCHDOG_NOTICE;
    }
    watchdog('uibx', $message, NULL, $severity);
  }
}
