#!/bin/bash
cd /var/www/w3.uib.no
#Needs to be run 2x times (due to bugs in sebra, first run filles cache)
date +'%H:%M ----------------------------------------------'    >>/tmp/drupal-uib-sebra-areas.$(date -I).log
nice -n 20 su w3-drupal -c 'bin/site-drush uib-sebra-areas -v'  >>/tmp/drupal-uib-sebra-areas.$(date -I).log 2>&1
date +'%H:%M ----------------------------------------------'    >>/tmp/drupal-uib-sebra-areas.$(date -I).log 2>&1
nice -n 20 su w3-drupal -c 'bin/site-drush uib-sebra-areas -v'  >>/tmp/drupal-uib-sebra-areas.$(date -I).log 2>&1
date +'%H:%M ----------------------------------------------'    >>/tmp/drupal-uib-sebra-places.$(date -I).log 2>&1
nice -n 20 su w3-drupal -c 'bin/site-drush uib-sebra-places -v' >>/tmp/drupal-uib-sebra-places.$(date -I).log 2>&1
date +'%H:%M ----------------------------------------------'    >>/tmp/drupal-uib-sebra-places.$(date -I).log 2>&1
nice -n 20 su w3-drupal -c 'bin/site-drush uib-sebra-places -v' >>/tmp/drupal-uib-sebra-places.$(date -I).log 2>&1
date +'%H:%M ----------------------------------------------'             >>/tmp/drupal-uib-sebra-users.$(date -I).log 2>&1
nice -n 20 su w3-drupal -c 'bin/site-drush uib-sebra-users --limit=0 -v' >>/tmp/drupal-uib-sebra-users.$(date -I).log 2>&1
date +'%H:%M ----------------------------------------------'             >>/tmp/drupal-uib-sebra-users.$(date -I).log 2>&1
nice -n 20 su w3-drupal -c 'bin/site-drush uib-sebra-users --limit=0 -v' >>/tmp/drupal-uib-sebra-users.$(date -I).log 2>&1
