<?php
/**
 * @file
 * Code for the UiB Feature Area feature.
 */

include_once 'uib_feature_area.features.inc';

/**
 * Implements hook_menu_block_blocks
 */

function uib_feature_area_menu_block_blocks() {
  return array(
    'top-area-menu' => array(
      'menu_name'   => 'area',
      'title_link'  => FALSE,
      'admin_title' => 'Top level area menu',
      'level'       => 2,
      'depth'       => 2,
      'expanded'    => 1,
    ),
    'page-area-menu' => array(
      'menu_name'   => 'area',
      'title_link'  => FALSE,
      'admin_title' => 'Page level area menu',
      'follow'      => 1,
      'level'       => 4,
      'depth'       => 1,
    ),
  );
}


/**
 * Implements hook_block_info().
 */

function uib_feature_area_block_info() {
  return array(
    'colophon' => array(
      'info' => t('Colophone'),
      'status' => TRUE,
    ),
  );
}


/**
 * Implements hook_block_view().
 */

function uib_feature_area_block_view($delta='') {
  $block = array();
  switch ($delta) {
  case 'colophon':
    $block['subject'] = t('Colophone');
    $block['content'] = 'Universitetet i Bergen | Foo';
    break;
  }
  return $block;
}
