<?php
/**
 * @file
 * Code for the UiB Feature Area feature.
 */

include_once 'uib_feature_area.features.inc';

/**
 * Implements hook_menu_block_blocks
 */

function uib_feature_area_menu_block_blocks() {
  return array(
    'top-area-menu' => array(
      'menu_name'   => 'area',
      'title_link'  => FALSE,
      'admin_title' => 'Top level area menu',
      'level'       => 2,
      'depth'       => 2,
      'expanded'    => 1,
    ),
    'page-area-menu' => array(
      'menu_name'   => 'area',
      'title_link'  => FALSE,
      'admin_title' => 'Page level area menu',
      'follow'      => 1,
      'level'       => 4,
      'depth'       => 1,
    ),
  );
}


/**
 * Implements hook_block_info().
 */

function uib_feature_area_block_info() {
  return array(
    'colophon' => array(
      'info' => t('Colophone'),
      'status' => TRUE,
    ),
  );
}


/**
 * Implements hook_block_view().
 */

function uib_feature_area_block_view($delta='') {
  $block = array();
  switch ($delta) {
  case 'colophon':
    $block['subject'] = t('Colophone');
    $block['content'] = array(
      'name' => array(
        '#type' => 'html_tag',
        '#tag' => 'h3',
        '#value' => t('University of Bergen'),
      ),
      'address' => array(
        '#theme' => 'key_value',
        '#key' => t('Address'),
        '#value' => 'Postboks 7800, 5020 BERGEN',
      ),
      'phone' => array(
        '#theme' => 'key_value',
        '#key' => t('Phone'),
        '#value' => '+47 55 58 00 00',
      ),
      'fax' => array(
        '#theme' => 'key_value',
        '#key' => t('Fax'),
      ),
      'emergency' => array(
        '#theme' => 'key_value',
        '#key' => t('24-hour security hotline'),
        '#value' => '+47 55 58 80 81',
      ),
      'responsible_this_page' => array(
        '#theme' => 'key_value',
        '#key' => t('Responsible for this page'),
      ),
      'contact' => array(
        '#theme' => 'key_value',
        '#key' => t('Contact'),
        '#value' => 'post@uib.no',
      ),
      'responsible' => array(
        '#theme' => 'key_value',
        '#key' => t('Responsible'),
        '#value' => t('Director of Communications'),
      ),
    );
    if (arg(0) == 'node' && is_numeric(arg(1))) {
      $node = node_load(arg(1));
      if ($node->type == 'area') {
        $area = $node;
      }
      elseif (isset($node->field_uib_area)) {
        $area = $node->field_uib_area['und'][0]['entity'];
      }
      if ($area) {
        $place = node_load($area->field_uib_ou['und'][0]['target_id']);
        $block['content']['name']['#value'] .= ' | ' . check_plain($area->title);
        //dsm($place);
        $block['content']['responsible_this_page']['#value'] = $place->title;
        if (isset($place->field_uib_phone)) {
          $block['content']['phone']['#value'] =
            $place->field_uib_phone['und'][0]['value'];
        }
        if (isset($place->field_uib_fax)) {
          $block['content']['fax']['#value'] =
            $place->field_uib_fax['und'][0]['value'];
        }
        if (isset($place->field_uib_mail_domain)) {
          $block['content']['contact']['#value'] =
            'post@' . $place->field_uib_mail_domain['und'][0]['safe_value'];
        }
      }
      hide($block['content']['emergency']);
    }
    break;
  }
  //dsm($block);
  return $block;
}

/**
 * Implements hook_field_formatter_info().
 */
function uib_feature_area_field_formatter_info() {
  return array(
    'uib_feature_area_link_feed' => array(
      'label' => t('View as an rss feed'),
      'field types' => array('link_field'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_view()
 */
function uib_feature_area_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $elements = array();

   foreach ($items as $delta => $item) {
    $content = @file_get_contents($item['url']);
    if (!$content)
      continue;
    $elements[$delta] = array(
      'list' => array(
        '#title' => $item["title"],
        '#items' => array(),
        '#theme' => 'item_list',
      ),
    );
    $xml = new SimpleXmlElement($content);
    $limit = 5;
    foreach ($xml->channel->item as $entry) {
      $elements[$delta]['list']['#items'][] = l($entry->title, $entry->link) ;
      if (--$limit == 0)
        break;
    }
  }
  return $elements;
}

/**
 * Implements hook_theme().
 */
function uib_feature_area_theme() {
  return array(
    'uib_feature_area_formatter_uib_feature_area_link_feed' => array(
      'variables' => array('element' => NULL),
    ),
  );
}