<?php
/**
 * @file
 * Code for the UiB Feature Area feature.
 */

include_once 'uib_feature_area.features.inc';

/**
 * Implements hook_menu_block_blocks
 */

function uib_feature_area_menu_block_blocks() {
  return array(
    'top-area-menu' => array(
      'menu_name'   => 'area',
      'title_link'  => FALSE,
      'admin_title' => 'Top level area menu',
      'level'       => 2,
      'depth'       => 2,
      'expanded'    => 1,
    ),
    'page-area-menu' => array(
      'menu_name'   => 'area',
      'title_link'  => FALSE,
      'admin_title' => 'Page level area menu',
      'follow'      => 1,
      'level'       => 4,
      'depth'       => 1,
    ),
  );
}


/**
 * Implements hook_block_info().
 */

function uib_feature_area_block_info() {
  return array(
    'colophon' => array(
      'info' => t('Colophone'),
      'status' => TRUE,
    ),
  );
}


/**
 * Implements hook_block_view().
 */

function uib_feature_area_block_view($delta='') {
  $block = array();
  switch ($delta) {
  case 'colophon':
    $block['subject'] = t('Colophone');
    $block['content'] = array(
      'name' => array(
        '#prefix' => '<h3>',
        '#suffix' => '</h3>',
        '#markup' => t('University of Bergen'),
      ),
      'address' => array(
        '#prefix' => '<br>' . t('Address: '),
        '#markup' => 'Postboks 7800, 5020 BERGEN',
      ),
      'tlf' => array(
        '#prefix' => '<br>' . t('Phone: '),
        '#markup' => '55 58 00 00',
      ),
      'fax' => array(),
      'emergency' => array(
        '#prefix' => '<br>' . t('24-hour security hotline: '),
        '#markup' => '55 58 80 81',
      ),
      'contact' => array(
        '#prefix' => '<br>' . t('Contact: '),
        '#markup' => 'post@uib.no',
      ),
      'responsible' => array(
        '#prefix' => '<br>' . t('Responsible: '),
        '#markup' => t('Director of Communications'),
      ),
    );
    if (arg(0) == 'node' && is_numeric(arg(1))) {
      $node = node_load(arg(1));
      if ($node->type == 'area') {
        $area = $node;
      }
      elseif (isset($node->field_uib_area)) {
        $area = $node->field_uib_area['und'][0]['entity'];
      }
      if ($area) {
        $block['content']['name']['#markup'] = 'Universitetet i Bergen | ' . $area->title;
      }
      unset($block['content']['emergency']);
    }
    break;
  }
  //dsm($block);
  return $block;
}
