<?php
/**
 * @file
 * uib_article.field_group.inc
 */

/**
 * Implements hook_field_group_info().
 */
function uib_article_field_group_info() {
  $export = array();

  $field_group = new stdClass();
  $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
  $field_group->api_version = 1;
  $field_group->identifier = 'group_article_sidebar|node|uib_article|default';
  $field_group->group_name = 'group_article_sidebar';
  $field_group->entity_type = 'node';
  $field_group->bundle = 'uib_article';
  $field_group->mode = 'default';
  $field_group->parent_name = '';
  $field_group->data = array(
    'label' => 'article-sidebar',
    'weight' => '5',
    'children' => array(
      0 => 'field_uib_deadline',
      1 => 'field_uib_registration_link',
      2 => 'field_uib_files',
      3 => 'field_uib_links',
      4 => 'field_uib_contacts',
      5 => 'field_uib_location',
      6 => 'field_uib_event_type',
      7 => 'field_uib_media',
      8 => 'field_uib_date',
      9 => 'field_uib_fact_box',
    ),
    'format_type' => 'div',
    'format_settings' => array(
      'label' => 'article-sidebar',
      'instance_settings' => array(
        'classes' => ' group-article-sidebar field-group-div',
        'description' => '',
        'show_label' => '0',
        'label_element' => 'h3',
        'effect' => 'none',
        'speed' => 'fast',
      ),
      'formatter' => 'open',
    ),
  );
  $export['group_article_sidebar|node|uib_article|default'] = $field_group;

  $field_group = new stdClass();
  $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
  $field_group->api_version = 1;
  $field_group->identifier = 'group_information|node|uib_article|form';
  $field_group->group_name = 'group_information';
  $field_group->entity_type = 'node';
  $field_group->bundle = 'uib_article';
  $field_group->mode = 'form';
  $field_group->parent_name = '';
  $field_group->data = array(
    'label' => 'Information',
    'weight' => '2',
    'children' => array(
      0 => 'field_uib_relation',
      1 => 'field_uib_show_global_calendar',
      2 => 'field_uib_related_persons',
      3 => 'field_uib_event_type',
      4 => 'field_uib_area',
      5 => 'field_uib_byline',
      6 => 'field_related_persons_label',
      7 => 'field_uib_text',
      8 => 'field_uib_main_media',
      9 => 'field_uib_kicker',
      10 => 'field_uib_lead',
      11 => 'field_uib_article_type',
      12 => 'field_uib_external_author',
      13 => 'title',
    ),
    'format_type' => 'div',
    'format_settings' => array(
      'label' => 'Information',
      'instance_settings' => array(
        'required_fields' => 1,
        'classes' => 'clearfix group-information field-group-div',
        'description' => '',
        'show_label' => '0',
        'label_element' => 'h3',
        'effect' => 'none',
        'speed' => 'fast',
      ),
      'formatter' => 'open',
    ),
  );
  $export['group_information|node|uib_article|form'] = $field_group;

  $field_group = new stdClass();
  $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
  $field_group->api_version = 1;
  $field_group->identifier = 'group_related_persons|node|uib_article|default';
  $field_group->group_name = 'group_related_persons';
  $field_group->entity_type = 'node';
  $field_group->bundle = 'uib_article';
  $field_group->mode = 'default';
  $field_group->parent_name = '';
  $field_group->data = array(
    'label' => 'Related persons group',
    'weight' => '6',
    'children' => array(
      0 => 'field_uib_related_persons',
      1 => 'field_related_persons_label',
    ),
    'format_type' => 'html5',
    'format_settings' => array(
      'label' => 'Related persons group',
      'instance_settings' => array(
        'classes' => 'group-related-persons field-group-html5',
        'wrapper' => 'section',
      ),
    ),
  );
  $export['group_related_persons|node|uib_article|default'] = $field_group;

  $field_group = new stdClass();
  $field_group->disabled = FALSE; /* Edit this to true to make a default field_group disabled initially */
  $field_group->api_version = 1;
  $field_group->identifier = 'group_sidebar|node|uib_article|form';
  $field_group->group_name = 'group_sidebar';
  $field_group->entity_type = 'node';
  $field_group->bundle = 'uib_article';
  $field_group->mode = 'form';
  $field_group->parent_name = '';
  $field_group->data = array(
    'label' => 'Sidebar',
    'weight' => '1',
    'children' => array(
      0 => 'field_uib_deadline',
      1 => 'field_uib_contacts',
      2 => 'field_uib_registration_link',
      3 => 'field_uib_location',
      4 => 'field_uib_links',
      5 => 'field_uib_files',
      6 => 'field_uib_fact_box',
      7 => 'field_uib_date',
      8 => 'field_uib_media',
    ),
    'format_type' => 'div',
    'format_settings' => array(
      'label' => 'Sidebar',
      'instance_settings' => array(
        'required_fields' => 1,
        'classes' => 'clearfix group-sidebar field-group-div',
        'description' => '',
        'show_label' => '0',
        'label_element' => 'h3',
        'effect' => 'none',
        'speed' => 'fast',
      ),
      'formatter' => 'open',
    ),
  );
  $export['group_sidebar|node|uib_article|form'] = $field_group;

  return $export;
}
