<?php
/**
 * @file
 * uib_area.context.inc
 */

/**
 * Implements hook_context_default_contexts().
 */
function uib_area_context_default_contexts() {
  $export = array();

  $context = new stdClass();
  $context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
  $context->api_version = 3;
  $context->name = 'ansattside_blocks';
  $context->description = 'Blocks that are unique to employee pages';
  $context->tag = 'block';
  $context->conditions = array(
    'path' => array(
      'values' => array(
        'foransatte' => 'foransatte',
        'foransatte/*' => 'foransatte/*',
        'en/foremployees' => 'en/foremployees',
        'en/foremployees/*' => 'en/foremployees/*',
      ),
    ),
  );
  $context->reactions = array(
    'block' => array(
      'blocks' => array(
        'system-main' => array(
          'module' => 'system',
          'delta' => 'main',
          'region' => 'content',
          'weight' => '-10',
        ),
      ),
    ),
  );
  $context->condition_mode = 0;

  // Translatables
  // Included for use with string extractors like potx.
  t('Blocks that are unique to employee pages');
  t('block');
  $export['ansattside_blocks'] = $context;

  $context = new stdClass();
  $context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
  $context->api_version = 3;
  $context->name = 'area_blocks';
  $context->description = '';
  $context->tag = 'block';
  $context->conditions = array(
    'node' => array(
      'values' => array(
        'area' => 'area',
        'uib_article' => 'uib_article',
        'uib_testimonial' => 'uib_testimonial',
      ),
      'options' => array(
        'node_form' => '0',
      ),
    ),
    'views' => array(
      'values' => array(
        'ansatte' => 'ansatte',
        'area_map' => 'area_map',
        'calendar' => 'calendar',
        'courses' => 'courses',
        'recent_news:newsarchive' => 'recent_news:newsarchive',
      ),
    ),
  );
  $context->reactions = array(
    'block' => array(
      'blocks' => array(
        'uib_area-area_parents' => array(
          'module' => 'uib_area',
          'delta' => 'area_parents',
          'region' => 'sidebar_second',
          'weight' => '-10',
        ),
        'views-calendar-block_1' => array(
          'module' => 'views',
          'delta' => 'calendar-block_1',
          'region' => 'sidebar_second',
          'weight' => '-9',
        ),
        'views-calendar-block_4' => array(
          'module' => 'views',
          'delta' => 'calendar-block_4',
          'region' => 'sidebar_second',
          'weight' => '-8',
        ),
        'views-recent_news-block' => array(
          'module' => 'views',
          'delta' => 'recent_news-block',
          'region' => 'sidebar_second',
          'weight' => '-7',
        ),
        'uib_area-feed' => array(
          'module' => 'uib_area',
          'delta' => 'feed',
          'region' => 'sidebar_second',
          'weight' => '-6',
        ),
        'uib_area-paahoyden_logo' => array(
          'module' => 'uib_area',
          'delta' => 'paahoyden_logo',
          'region' => 'sidebar_second',
          'weight' => '-5',
        ),
        'uib_area-jobbnorge' => array(
          'module' => 'uib_area',
          'delta' => 'jobbnorge',
          'region' => 'sidebar_second',
          'weight' => '-4',
        ),
        'views-relevant_links-relevant_links' => array(
          'module' => 'views',
          'delta' => 'relevant_links-relevant_links',
          'region' => 'sidebar_second',
          'weight' => '-3',
        ),
        'views-79622ce408d27be255f959dc886a6751' => array(
          'module' => 'views',
          'delta' => '79622ce408d27be255f959dc886a6751',
          'region' => 'sidebar_second',
          'weight' => '-2',
        ),
        'views-e35933dcbeaec830701d3e48e98f0046' => array(
          'module' => 'views',
          'delta' => 'e35933dcbeaec830701d3e48e98f0046',
          'region' => 'sidebar_second',
          'weight' => '-1',
        ),
        'views-59c9268577c7dee7af4089857ed7ab4e' => array(
          'module' => 'views',
          'delta' => '59c9268577c7dee7af4089857ed7ab4e',
          'region' => 'sidebar_second',
          'weight' => '0',
        ),
        'views-87d291272c77934f60566c1a5bccebdf' => array(
          'module' => 'views',
          'delta' => '87d291272c77934f60566c1a5bccebdf',
          'region' => 'sidebar_second',
          'weight' => '1',
        ),
      ),
    ),
  );
  $context->condition_mode = 0;

  // Translatables
  // Included for use with string extractors like potx.
  t('block');
  $export['area_blocks'] = $context;

  return $export;
}
