#!/bin/sh

PATH=$HOME/firefox:$PATH

if [ ! -d mypy ]; then
    virtualenv --no-site-packages --distribute mypy
    mypy/bin/pip --quiet install -r requirements.txt
fi

source mypy/bin/activate

rm -f *.png
./runtests --headless "$@"
