<?php
/**
 * @file
 * Code for the UiB Feature User feature.
 */

include_once 'uib_user.features.inc';

/**
 * Implements hook_username_alter().
 *
 * The UiB user names are too ugly to show to regular people, so we want
 * users to be presented by their "<first name> <last name>".
 */

function uib_user_username_alter(&$name, $account) {
  if (isset($account->uid)) {
    $user = user_load($account->uid);
    if (!empty($user->field_uib_first_name)) {
      $name = $user->field_uib_first_name['und'][0]['safe_value'];
      if (!empty($user->field_uib_last_name)) {
        $name = "$name " . $user->field_uib_last_name['und'][0]['safe_value'];
      }
    }
    else {
      $name = "[$name]";
    }
  }
}

/**
 * Implements hook_user_login().
 */
function uib_user_user_login(&$edit, $account) {
  if ( (in_array('level 1', $account->roles, TRUE)) || ($account->uid == 1) || (in_array('level 2', $account->roles, TRUE)) || (in_array('level 3', $account->roles, TRUE)) ) {
    $edit['redirect'] = 'webdesk';
  }
  else {
    $edit['redirect'] = 'user';
  }
}

/**
 * Implements hook_theme().
 *
 */
function uib_user_theme($existing, $type, $theme, $path) {
  return array(
    'views_view_field__user_block__edit_node' => array(
      'arguments' => array('view' => FALSE, 'field' => FALSE, 'row' => FALSE),
      'original hook' => 'views_view_field',
    ),
  );
}

function theme_views_view_field__user_block__edit_node($view) {
  global $user;
  global $language;
  $alias = drupal_get_path_alias('user/' . $user->uid);

  if ('user/' . $user->uid != $alias) {
    $url = '<a href=http://uib.no/' . $alias . '>' . t('Edit account') . '</a';
    return $url;
  }
}

/**
 * Implements hook_user_presave().
 */
function uib_user_user_presave(&$edit, $account, $category) {
  if (isset($edit['field_uib_last_name']['und'])) {
    $edit['field_uib_sort_name']['und'][0]['value'] = uibx_sort_name($edit['field_uib_last_name']['und'][0]['value']);
  }
}

/**
 * Implements hook_form_alter().
 *
 */
function uib_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login') {
    array_unshift($form['#validate'], 'uib_user__username_lc');
  }
  if ($form['#form_id'] == 'user_profile_form') {
    field_group_hide_field_groups($form, array('group_uib_hidden'));
    $profile_user = entity_metadata_wrapper('user', $form['#user']);
    if ($profile_user->field_uib_position_category->value() == 'faculty') {
      $form['field_uib_user_field'][$form['field_uib_user_field']['#language']][0]['#title'] = t('Research');
    }
    elseif ($profile_user->field_uib_position_category->value() == 'staff') {
      $form['field_uib_user_field'][$form['field_uib_user_field']['#language']][0]['#title'] = t('Work');
    }

    // Disable fields that are synchronized with SEBRA
    $synchronized_properties = array(
      'name',
      'mail',
      // 'status', // These are synchronized but Level 1 wants to be able to edit them
      // 'roles',
    );
    foreach ($synchronized_properties as $item) {
      $form['account'][$item]['#disabled'] = TRUE;
    }
    $synchronized_fields = array(
      'field_uib_user_alt_firstname',
      'field_uib_user_alt_lastname',
      'field_uib_sort_name',
      'field_uib_phone',
      'field_uib_position',
      'field_uib_position_code',
      'field_uib_position_category',
    );
    foreach ($synchronized_fields as $item) {
      $form[$item]['#disabled'] = TRUE;
    }

    $hidden_properties_level_2_and_3 = array(
      'mail',
      'pass',
      'current_pass',
    );
    if (!in_array('level 1', $GLOBALS['user']->roles, TRUE)) {
      foreach ($hidden_properties_level_2_and_3 as $item) {
        $form['account'][$item]['#access'] = FALSE;
      }
    }

    $hidden_fields_not_level_1 = array(
      'field_uib_user_domain',
    );
    if (!in_array('level 1', $GLOBALS['user']->roles, TRUE)) {
      foreach ($hidden_fields_not_level_1 as $item) {
        $form[$item]['#access'] = FALSE;
      }
    }

    $hidden_fields = array(
      'field_uib_phone',
    );
    foreach ($hidden_fields as $item) {
      $form[$item]['#access'] = FALSE;
    }
  }
}

/**
 * Always lowercase username.
 *
 */
function uib_user__username_lc($form, &$form_state) {
  if (!empty($form_state['values']['name'])) {
    $form_state['values']['name'] = drupal_strtolower($form_state['values']['name']);
  }
}

/**
 * Implements hook_custom_theme().
 */
function uib_user_custom_theme() {
  $arg = arg();
  if (isset($arg[2])) {
    if ($arg[0] == 'user' && $arg[2] == 'edit') {
      return 'uib_zen';
    }
  }
}

/**
 * Implements hook_block_info().
 *
 */
function uib_user_block_info() {
  return array(
    'research_groups' => array(
      'info' => t("User's research groups"),
      'status' => TRUE,
    ),
    'feed' => array(
       'info' => t("User's RSS feed"),
       'status' => TRUE,
    ),
    'twitter' => array(
      'info' => t("User's twitter timeline"),
      'status' => TRUE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function uib_user_block_view($delta='') {
  global $language;
  $block = array();
  $uid = ((arg(0) == 'user' && is_numeric(arg(1))) ? arg(1) : FALSE);
  switch ($delta) {
    case 'research_groups':
      if ($uid) {
        // Find research groups that this user belongs to
        $query = new EntityFieldQuery;
        $result = $query
          ->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'area')
          ->fieldCondition('field_uib_staff', 'target_id', $uid)
          ->fieldCondition('field_uib_area_type', 'value', 'research group')
          ->execute();
        if (!empty($result)) {
          $areas = entity_load('node', array_keys($result['node']));
          foreach ($areas as $nid => $research_grp) {
            if ($research_grp->language == $language->language) {
              $block['content'][]['#markup'] = '<div>' . l($research_grp->title, "node/$nid") . '</div>';
            }
          }
          if ($block) {
            $block['subject'] = t('Research groups');
          }
        }
      }
    break;
    case 'feed':
      if ($uid) {
        $user = user_load(intval($uid));
        if($user){
          $elements = array();
          if (!empty($user->field_uib_user_feed['und'])) {
            foreach ($user->field_uib_user_feed['und'] as $delta => $item) {
              $url = url($item['url'], $item);
              if (strpos($url, '#')) {
                $limit = explode('#', $url);
              }
              $limit = (isset($limit[1]) && is_numeric($limit[1])) ? $limit[1] : 5;
              $elements[$delta] = uib_feed__format($url, $item['title'], $limit, array('uib_user__feed_format_post_render'));
            }
          }
          $block['content'] = $elements;
        }
      }
    break;
    case 'twitter':
      if ($uid) {
        $user = user_load(intval($uid));
        if($user){
          $elements = '';
          if (!empty($user->field_uib_user_social_media['und'])) {
            foreach ($user->field_uib_user_social_media['und'] as $delta => $item) {
              if (preg_match('/twitter:(.*)/', $item['safe_value'], $twitter_handle)){
                $twitter_handle = $twitter_handle[1];
                $elements .= '<a class="twitter-timeline" href="https://twitter.com/"' . $twitter_handle .
                  ' data-widget-id="504179221749456896" data-screen-name="' . $twitter_handle .
                  '" height="350" data-chrome="noheader nofooter">' .
                  t('Tweets by @@twitter_handler', array('@twitter_handler' =>  $twitter_handle)) . '</a>';
              }
            }
            if ($elements != ''){
              $block['subject'] = 'Twitter';
              $block['content'] = $elements . '<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?"http":"https";if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>';
            }
          }
        }
      }
    break;
  }
  return $block;
}

/**
 * Implements hook_preprocess_page()
 */
function uib_user_preprocess_page(&$vars) {
  $unwanted_tabs_level_2_and_3 = array('user/%/scheduler');
  global $user;
  if (!in_array('level 1', $user->roles)) {
    foreach ($vars['tabs'] as $tabs_key => $tabs) {
      if (is_array($tabs)) {
        foreach ($tabs as $tab_key => $tab) {
          if (isset($tab['#link']['path']) && in_array($tab['#link']['path'], $unwanted_tabs_level_2_and_3)) {
            unset($vars['tabs'][$tabs_key][$tab_key]);
          }
        }
      }
    }
  }
}

/**
 * Implements hook_user_view_alter().
 */
function uib_user_user_view_alter(&$build) {
  drupal_add_library('system' , 'ui.tabs');
  drupal_add_js(drupal_get_path('theme', 'uib_zen') . '/js/tabs.js', array('group' => JS_THEME, ));

  $profile_user = entity_metadata_wrapper('user', $build['#account']);

  // Add email address with markup as if it was a field
  $build['user_email'] = array(
    '#weight' => 15,
    '#markup' => uib_user_add_field_markup(t('E-mail'), 'uib-user-email', l($profile_user->mail->value(), 'mailto:' . $profile_user->mail->value(), array('absolute' => TRUE))),
  );

  // Add a vcard download link
  if ($build['#account']->field_uib_user_domain['und'][0]['value'] == 'uib') {
    $vcard_url = 'user/' . $build['#account']->uid . '/card.vcf';
    $build['user_vcard_link'] = array(
      '#weight' => 98,
      '#markup' => l(t('Download vCard'), $vcard_url, array(
        'attributes' => array('class' => 'uib-user-vcard'),
      )),
    );
  }

  // Add login link inside card
  if ($build['#view_mode'] == 'full' && !user_is_logged_in()) {
    $options = array();
    $options['attributes']['class'] = 'uib-user-login-link';
    $options['query']['destination'] = 'user';
    $link_url = 'user';
    $build['user_login_incard_link'] = array (
      '#weight' => 99,
      '#markup' => l(t('Log in'), 'user', $options),
    );
  }

  // Move stuff into field groups
  $build['#group_children']['user_picture'] = 'group_user_media';
  $build['#group_children']['user_email'] = 'group_user_contact';
  $build['#group_children']['user_vcard_link'] = 'group_media_element';
  $build['#group_children']['user_login_incard_link'] = 'group_media_element';
  $build['#group_children']['selected_publications'] = 'group_user_first';

  // Manage field overrides
  global $language;
  if (isset($build['field_uib_user_ou'])) {
    $ou_nid = $build['field_uib_user_ou']['#items'][0]['target_id'];
    unset($build['field_uib_user_ou'][0]['node'][$ou_nid]['#contextual_links']);
    if (!empty($build['#account']->field_uib_user_alt_address[$language->language][0]['thoroughfare'])) {
      foreach ($build['#account']->field_uib_user_alt_address[$language->language][0] as $item_name => $item) {
        if (isset($build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_visit_address'][0]['#address'][$item_name])) {
          $build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_visit_address'][0]['#address'][$item_name] = $item;
        }
      }
    }
    // Move address fields out of ou div
    if (isset($build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_visit_address'])) {
      $build['visit_address'] = $build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_visit_address'];
      unset($build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_visit_address']);
      $build['visit_address']['#weight'] = 1;
      $build['#group_children']['visit_address'] = 'group_user_ci_2';
    }
    if (isset($build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_postal_address'])) {
      $build['postal_address'] = $build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_postal_address'];
      unset($build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_postal_address']);
      $build['postal_address']['#weight'] = 3;
      $build['#group_children']['postal_address'] = 'group_user_ci_2';
    }
    // Add a relevant area link to name of connected ou
    if ($relevant_area = uib_user__ou_area($ou_nid, $build['#account']->uid)) {
      $area = entity_load_single('node', $relevant_area);
      $build['field_uib_user_ou'][0]['node'][$ou_nid]['field_uib_ou_title'][0]['#markup'] = l($area->title, 'node/' . $relevant_area);
    }
  }

  if (!empty($build['field_uib_user_alt_position'][0]['#markup'])) {
    $build['field_uib_user_alt_position'][0]['#markup'] = ', ' . $build['field_uib_user_alt_position'][0]['#markup'];
  }

  if (!empty($build['field_uib_user_field'])) {
    if ($profile_user->field_uib_position_category->value() == 'faculty') {
      $build['field_uib_user_field']['#title'] = t('Research');
    }
    elseif ($profile_user->field_uib_position_category->value() == 'staff') {
      $build['field_uib_user_field']['#title'] = t('Work');
    }
  }

  // Tabs
  $tabs_field_list = array();
  foreach ($build['#group_children'] as $field_name => $group_name) {
    if ($group_name == 'group_user_work_1' && isset($build[$field_name]['#weight'])) {
      $tabs_field_list[$field_name] = $build[$field_name]['#weight'];
    }
  }
  asort($tabs_field_list);
  foreach ($tabs_field_list as $field_name => $weight) {
    unset($tabs_field_list[$field_name]);
    $tabs_field_list[$field_name]['weight'] = $weight;
    $tabs_field_list[$field_name]['title'] = $build[$field_name]['#title'];
    $tabs_field_list[$field_name]['htmltitle'] = 'uib-tabs-' . mb_ereg_replace('[^a-z0-9]+', '-', drupal_strtolower($build[$field_name]['#title']));
  }
  // Manage the optional tab if it has a name
  if (isset($tabs_field_list['field_uib_user_opt_title'])) {
    $tabs_field_list['field_uib_user_opt_content']['title'] = $build['field_uib_user_opt_title']['#items'][0]['safe_value'];
    hide($build['field_uib_user_opt_title']);
    unset($tabs_field_list['field_uib_user_opt_title']);
    $tabs_field_list['field_uib_user_opt_content']['htmltitle'] = 'uib-tabs-' . mb_ereg_replace('[^a-z0-9]+', '-', drupal_strtolower($tabs_field_list['field_uib_user_opt_content']['title']));
    $build['field_uib_user_opt_content']['#title'] = $tabs_field_list['field_uib_user_opt_content']['title'];
  }
  else {
    hide($build['field_uib_user_opt_title']);
    unset($tabs_field_list['field_uib_user_opt_title']);
    hide($build['field_uib_user_opt_content']);
    unset($tabs_field_list['field_uib_user_opt_content']);
  }
  $tabs_list_markup = '<ul class="uib-tabs-list">';
  foreach ($tabs_field_list as $field_name => $tabs_item) {
    $tabs_list_markup .= '<li><a href="#' . $tabs_item['htmltitle'] . '">' . $tabs_item['title'] . '</a></li>';
    $build[$field_name]['#prefix'] = '<div id="' . $tabs_item['htmltitle'] . '">';
    $build[$field_name]['#suffix'] = '</div>';
    $build[$field_name]['#label_display'] = 'hidden';
  }
  $tabs_list_markup .= '</ul>';
  $build['uib_tabs'] = array(
    '#weight' => 24,
    '#markup' => $tabs_list_markup,
    );
  $build['#group_children']['uib_tabs'] = 'group_user_work_1';

  // Current projects field collapsible
  if (isset($build['field_uib_user_projects'][0]['#markup'])) {
    $field_collapsed = FALSE;
    $tmp = trim(strip_tags($build['field_uib_user_projects'][0]['#markup']));
    if (strlen($tmp) > 200) {
      $field_collapsed = TRUE;
    }
    $build['field_uib_user_projects'][0]['#markup'] = theme(
      'ctools_collapsible',
      array(
        'handle' => $build['field_uib_user_projects']['#title'],
        'content' => $build['field_uib_user_projects'][0]['#markup'],
        'collapsed' => $field_collapsed,
        )
      );
  }

  if ($build['#view_mode'] == 'uib_user_teaser') {
    $build['uib_user_teaser'] = uib_user__teaser_markup($build['#account']);
    if (isset($build['field_uib_first_name'])) unset($build['field_uib_first_name']);
    if (isset($build['field_uib_last_name'])) unset($build['field_uib_last_name']);
    unset($build['user_email']);
    unset($build['user_edit_link']);
    unset($build['user_vcard_link']);
  }

  // change field_uib_user_competence from taxonomy/term to persons
  if (!empty($build['field_uib_user_competence'])) {
    $items = count($build['field_uib_user_competence']['#items']);
    for ($i=0; $i < $items; $i++) {
      $tid = $build['field_uib_user_competence']['#items'][$i]['tid'];
      $build['field_uib_user_competence'][$i]['#href'] =
        url('persons', array('absolute' => TRUE, 'query' =>  array('field_uib_user_competence_tid' => $tid)));
    }
  }

  if (!empty($build['field_uib_user_cv'])) {
    $cv_file_url = file_create_url($build['field_uib_user_cv'][0]['#file']->uri);
    $cv_text = t('Show CV');
    $build['field_uib_user_cv'] = array(
      '#weight' => 5,
      '#markup' => l($cv_text, $cv_file_url),
    );
  }

  // Do not show user history
  hide($build['summary']);
}

/**
 * Implements hook_field_formatter_info().
 */
function uib_user_field_formatter_info() {
  return array(
    'uib_strict_translation_formatter' => array(
      'label' => t('UiB strict EntityTranslation'),
      'field types' => array('text_long', 'text', 'link_field', 'taxonomy_term_reference'),
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function uib_user_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  if ($display['type'] == 'uib_strict_translation_formatter' && $field['translatable']) {
    // Formats fields only if content exists in the current language
    // i.e. Entity translation fallback setting is ignored.
    global $language;
    $elements = array();
    foreach ($items as $delta => $item) {
      if (!empty($entity->{$field['field_name']}[$language->language])) {
        // Translation exists
        if ($field['type'] == 'text' || $field['type'] == 'text_long') {
          $elements[$delta]['#markup'] = $item['safe_value'];
        }
        elseif ($field['type'] == 'link_field' ) {
          if ($field['field_name'] == 'field_uib_user_url') {
            $link_title = (empty($item['title']) || $item['title'] == $item['display_url']) ? t('Home Page') : check_plain($item['title']);
          }
          else {
            $link_title = $item['title'];
          }
          $elements[$delta]['#markup'] = l($link_title, $item['url'], array('attributes' => $item['attributes']));
        }
        elseif ($field['type'] == 'taxonomy_term_reference') {
          // Taxonomy term reference link
          $term = taxonomy_term_load($item['tid']);
          $uri = entity_uri('taxonomy_term', $term);
          $elements[$delta] = array(
            '#type' => 'link',
            '#title' => $term->name,
            '#href' => $uri['path'],
            '#options' => $uri['options'],
          );
        }
      }
    }
    return $elements;
  }
}


/**
 * Find the the most relevant home area for a user
 */
function uib_user__ou_area($ou_nid, $uid) {
  global $language;
  $area = NULL;
  // Get area (certain types) connected to ou
  $query = new EntityFieldQuery;
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'area')
    ->propertyCondition('language', $language->language)
    ->fieldCondition('field_uib_ou', 'target_id', $ou_nid)
    ->fieldCondition('field_uib_area_type', 'value', array('institute', 'faculty', 'unit'))
    ->execute();
  if (!empty($result['node'])) {
    $area_list = array_keys($result['node']);
    $area = $area_list[0];
    if (count($area_list) > 1) {
      uibx_log("User $uid had more than one optimal area [in function uib_user__ou_area]", "warning");
    }
  }
  else {
    // Get an area among staff connections for the user
    $query = new EntityFieldQuery;
    $result = $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'area')
      ->propertyCondition('language', $language->language)
      ->fieldCondition('field_uib_staff', 'target_id', $uid)
      ->fieldCondition('field_uib_area_type', 'value', array('institute', 'faculty', 'unit'))
      ->execute();
    if (!empty($result['node'])) {
      $area_list = array_keys($result['node']);
      $area = $area_list[0];
      if (count($area_list) > 1) {
        uibx_log("User $uid had more than one optimal staff area [in function uib_user__ou_area]", "warning");
      }
    }
  }
  return $area;
}

/**
 * Adds markup to a piece of html to make it look like a field
 */
function uib_user_add_field_markup($label, $class, $data) {
  return theme_field(array(
    'label' => $label,
    'label_hidden' => FALSE,
    'classes' => $class,
    'element' => array('#field_name' => ''),
    'items' => array(
      array(
        '#markup' => $data,
        ),
      ),
    'attributes' => '',
    'title_attributes' => '',
    'content_attributes' => '',
    'item_attributes' => array(0 => ''),
    )
  );
}

/**
 * Implements hook_menu().
 */
function uib_user_menu() {
  $items = array();

  $items['user/uib/%'] = array(
    'page callback' => 'uib_user__uname_lookup',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );

  $items['user/%user/card.vcf'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'uib_user__vcard_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Generate user redirect.
 */
function uib_user__uname_lookup($uname) {
  $u = user_load_by_name($uname);
  if ($u) {
    drupal_goto('user/' . $u->uid);
  }
  return MENU_NOT_FOUND;
}

/**
 * Generate vCard response for the given user.
 */
function uib_user__vcard_page($user_entity = NULL) {
  if (!empty($user_entity)) {
    drupal_add_http_header('Content-Type', 'application/vcard');
    $vcard = uib_user__vcard($user_entity);
    echo $vcard;
    return;
  }
  return MENU_NOT_FOUND;
}

/**
 * Generate the vCard for the given user.
 *
 * @param object $user_entity
 *
 * @return string
 * Vcard formatted data
 *
 */
function uib_user__vcard($user_entity) {
  $vc_user = entity_metadata_wrapper('user', $user_entity);
  // Name
  $first_name = $vc_user->field_uib_first_name->value();
  $last_name = $vc_user->field_uib_last_name->value();
  $full_name = "$first_name $last_name";

  // Position
  $title = $vc_user->field_uib_position->value();
  $title_alt = $vc_user->field_uib_user_alt_position->value();
  if (!empty($title_alt)) {
    $title .= ", $title_alt";
  }

  // Address
  $ou_address = $vc_user->field_uib_user_ou->field_uib_visit_address->value();
  $address_override = $vc_user->field_uib_user_alt_address->value();
  if (!empty($address_override)) {
    foreach ($address_override as $item => $value) {
      if (!empty($value) && $value != $ou_address[$item]) {
        $ou_address[$item] = $value;
      }
    }
  }

  $vcard = array();
  $vcard[] = 'BEGIN:VCARD';
  $vcard[] = 'VERSION:3.0';
  $vcard[] = "N:$last_name;$first_name;";
  $vcard[] = "FN:$full_name";
  $vcard[] = 'ORG:University of Bergen, ' . $vc_user->field_uib_user_ou->label();
  $vcard[] = "TITLE:$title";
  // $vcard[] = 'TEL;TYPE=WORK,VOICE:' . $vc_user->field_uib_phone->value();
  $vcard[] = 'TEL;TYPE=WORK,VOICE:' . $user_entity->field_uib_phone['und'][0]['value'];

  $adr = array();
  if (!empty($ou_address['thoroughfare'])) {
    $adr[] = $ou_address['thoroughfare'];
  }
  if (!empty($ou_address['postal_code'])) {
    $adr[] = $ou_address['postal_code'];
  }
  if (!empty($ou_address['locality'])) {
    $adr[] = $ou_address['locality'];
  }
  if ($ou_address['country'] == 'NO') {
    $adr[] = t('Norway');
  }
  $vcard[] = 'ADR;TYPE=WORK:;;' . implode(';', $adr);

  $vcard[] = 'EMAIL;TYPE=PREF,INTERNET:' . $vc_user->mail->value();
  $vcard[] = 'REV:' . date('c');
  $vcard[] = 'END:VCARD';
  $vcard[] = '';
  return implode("\n", $vcard);
}

/**
 * Implements hook_entity_info_alter()
 */
function uib_user_entity_info_alter(&$entity_info) {
  $entity_info['user']['view modes']['uib_user_teaser'] = array(
    'label' => t('User teaser'),
    'custom settings' => TRUE,
  );
}

/**
 * Generate markup for a teaser view mode for the given user
 *
 *  @param [object] $user a user entity
 *
 * @return [string] Markup for the view mode
 */
function uib_user__teaser_markup($user = NULL) {
  $markup = array(
    '#weight' => '1',
    );
  if (!empty($user)) {
    global $language;
    $lang = $language->language;
    $user_wrapper = entity_metadata_wrapper('user', $user, array('langcode' => $lang));
    $markup['#markup'] = '<div class="uib-user-teaser">';
    $full_name = $user_wrapper->field_uib_first_name->value() . ' ' . $user_wrapper->field_uib_last_name->value();
    $user_url = 'user/' . $user_wrapper->getIdentifier();
    $position = $user_wrapper->language($lang)->field_uib_position->value();
    if ($user_wrapper->language($lang)->field_uib_user_alt_position->value()) {
      $position .= ', ' . $user_wrapper->language($lang)->field_uib_user_alt_position->value();
    }
    $phone = $user_wrapper->field_uib_phone->value();
    $mail = $user_wrapper->mail->value();
    $markup['#markup'] .= '<h3>' . l($full_name, $user_url) . '</h3>';
    $markup['#markup'] .= '<p class="uib-user-position">' . $position . '</p>';
    if (!empty($phone)) $markup['#markup'] .= theme('item_list', array('items' => $phone, 'attributes' => array('class' => 'uib-user-phone')));
    $markup['#markup'] .= '<p class="uib-user-email">' . l($mail, 'mailto:' . $mail, array('absolute' => TRUE)) . '</p>';
    $markup['#markup'] .= '</div>';
  }
  return $markup;
}

/**
 * Implements hook_tag_alter()
 *
 * hook on tag term_access
 * taxonomy terms in fields of competence ordered by name
 */
function uib_user_query_term_access_alter(QueryAlterableInterface $query) {
    $query->orderBy('name');
}

/**
 * Changes the markup of a rendered RSS feed.
 *
 * @param [string] Markup for the RSS feed
 *
 */

function uib_user__feed_format_post_render($markup) {
  $markup = preg_replace('/<h3(.*?)>(.*?)<\/h3>/','<h2 class="block__title block-title">\2</h2>', $markup);
  return $markup;
}
