<?php

/**
 * Implements hook_views_query_alter().
 */
function uib_views_views_query_alter(&$view, &$query) {
  if ($view->name == 'ansatte') {

    if (!empty($query->where[0]['conditions'][0])) {
      $alias = '';
      foreach ($view->args as $value) {
        $alias .= $value . '/';
      }

      $alias = rtrim($alias, "/");
      $node = drupal_get_normal_path($alias, $language = NULL);

      if ($alias != $node) {
        $nid = substr(strrchr($node, "/"), 1);
        $query->where[0]['conditions'][0]['value'][':node_nid'] = $nid;
      }
    }
  }
}

/**
 * Implements hook_views_bulk_operations_form_alter().
 */
function uib_views_views_bulk_operations_form_alter(&$form, &$form_state, $vbo) {
  global $user;

  if (in_array('level 3', $user->roles)) {
    if (in_array('level 1', $user->roles) || in_array('level 2', $user->roles)) {
    }
    else {
      $form['select_all']['#access'] = FALSE;
      $form['select']['#access'] = FALSE;
      unset($form['views_bulk_operations']);
      unset($form['#parents']);
    }
  }
}

/**
 * Implements hook_block_view_alter().
 */
function uib_views_block_view_alter(&$data, $block) {
  if (!empty($data['subject'])) {
    if ($data['subject'] == 'Recent news') {
      if (uib_area__is_employee_page()) {
        $data['subject'] = 'Messages';
      }
    }
  }
}
