<?php
/**
 * Implements hook_theme().
 *
 */
function uib_views_theme($existing, $type, $theme, $path) {
  return array(
    'views_view_field__user_block__edit_node' => array(
      'arguments' => array('view' => FALSE, 'field' => FALSE, 'row' => FALSE),
      'original hook' => 'views_view_field',
    ),
  );
}

function theme_views_view_field__user_block__edit_node($view) {
  global $user;
  global $language;
  $alias = drupal_get_path_alias('user/' . $user->uid);

  if ('user/' . $user->uid != $alias) {
    $url = '<a href=http://uib.no/' . $alias . '>' . t('Edit account') . '</a';
    return $url;
  }
}
