#!/usr/bin/env python

import uib.web
import json
from collections import Counter

class XTopic(object):
    def __init__(self, etree):
        self.etree = etree

    def title(self):
        return self.etree.find('title').text

    def site(self):
        e = self.etree.find('site')
        return e.get('ref') if e is not None else None

    def topic_type(self):
        return self.etree.find('type').get('name')

    def title_type_site(self, site):
        res = self.title()
        res += ' ['
        t = self.topic_type()
        if t:
            res += t
        if self.site() != site:
            res += '*'
        res += ']'
        return res

    def nav_kids(self):
        site = self.etree.find('site')
        if site is not None:
            site = site.get('ref')
        for f in self.etree.findall('field'):
            if f.get('name') == 'menuorder' and f.get('scope') == site:
                return json.loads(f.text)
        return []

class XTopic_UserAgent(uib.web.UserAgent):
    prefix = "http://testbool.uib.no/"

    def get(self, url):
        if not url.startswith(("http:", "https")):
            url = self.prefix + url
        return super(XTopic_UserAgent, self).get(url)

    def _xtopic(self, etree):
        if etree is None:
            return None
        t = etree.find('topic')
        if t is None:
            return None
        return XTopic(t)

    def get_xtopic(self, xid):
        return self._xtopic(self.get_xml_etree('topicmap/@@xtopic?id=' + str(xid)))

    def get_xtopic_by_path(self, path):
        return self._xtopic(self.get_xml_etree(path + '/xtopic'))

def indent(depth):
    print '  ' * depth,

class Walker(object):
    def __init__(self, site):
        self.type_counter = Counter()
        self.site = site

    def walk(self, topic, depth=0):
        indent(depth)
        print topic.title_type_site(self.site).encode('UTF-8')
        self.type_counter[topic.topic_type()] += 1;
        for k in topic.nav_kids():
            t = ua.get_xtopic(k)
            if t:
                self.walk(t, depth + 1)
            else:
                indent(depth + 1)
                print '###', k, 'does not exist!'

ua = XTopic_UserAgent()
area = ua.get_xtopic_by_path("it")

walker = Walker(area.site())
walker.walk(area)

print
print walker.type_counter
