<?php
/**
 * @file
 * Code for the UiB Feature Testimonial feature.
 */

include_once 'uib_testimonial.features.inc';

/**
 * Implements hook_field_widget_form_alter.
 */
function uib_testimonial_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['type'] == 'entityreference' && $context['field']['field_name'] == 'field_uib_study_programmes') {
    if (!empty($element['target_id']['#default_value'])) {
      // Get study title that is translated into the language of the node being edited
      $study_nid = $context['items'][$context['delta']]['target_id'];
      $testimonial = entity_metadata_wrapper('node', $form_state['node']);
      $study = entity_metadata_wrapper('node', $testimonial->field_uib_study_programmes[$context['delta']]->value());
      $study_title = $study->language($form_state['node']->language)->field_uib_study_title->value();
      if (!empty($study_title)) {
        // Override form field default value
        $element['target_id']['#default_value'] = $study_title . ' (' . $study_nid . ')';
      }
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function uib_testimonial_node_presave($node) {
  if ($node->type == 'uib_testimonial') {
    // Set language of the testimonial to that of its mother area
    $area = node_load($node->field_uib_area['und'][0]['target_id']);
    $node->language = $area->language;
  }
}

/**
 * Implements hook_menu().
 */
function uib_testimonial_menu() {
  $items['node/%node/tmenu'] = array(
    'title' => 'Menu',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uib_testimonial_menu_form', 1),
    'access callback' => 'uib_testimonial__access_check',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

function uib_testimonial_menu_form($form, &$form_state, $node) {
  return uib_article_menu_local_task($form, $form_state, $node, 'uib_testimonial');
}

function uib_testimonial__access_check($node) {
  if (!empty($node)) {
    if ($node->type == 'uib_testimonial' && node_access('update', $node)) {
      if (!empty($node->field_uib_area['und'][0]['target_id'])) {
        return TRUE;
      }
    }
  }
  return FALSE;
}

function uib_testimonial_menu_form_submit($form, &$form_state) {
  uib_article_menu_local_task_submit($form, $form_state, 'uib_testimonial');
}
