#!/usr/bin/perl

use File::Basename qw(dirname);
chdir(dirname(__FILE__));
open(STDOUT, ">index.html") || die;

print <<'EOT';
<style>
body {
   margin: 20px;
}
img {
   background: #eee;
   padding: 20px;
   width: 200px;
   height: 200px;
}
</style>

<h1>Mockups</h1>

EOT

for my $png (sort <*.png>) {
    print <<EOT
<a href="$png"><img src="$png" title="$png"></a>
EOT
}
