<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function uib_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

function uib_migrate__sync_w2_users($limit=100) {
  $offset = variable_get('uib_w2_user_offset', 0);

  $query = new EntityFieldQuery;
  $query = $query
    ->entityCondition('entity_type', 'user')
    ->fieldCondition('field_uib_user_domain', 'value', 'uib', '=')
    ->range($offset, $limit);
  $result = $query->execute();

  $count = 0;
  foreach (array_keys($result['user']) as $uid) {
    $account = user_load($uid);
    uib_migrate__sync_w2_user($account->name);
    $count++;
  }

  variable_set('uib_w2_user_offset', $count < $limit ? 0 : $offset + $count);
}


/**
 * Fetch information about users still maintained in w2.
 *
 * This currently includes the slug and user picture.
 * A side effect of fetching the slug is to maintain path
 * aliases compatible with w2.
 */

function uib_migrate__sync_w2_user($username) {
  $account = user_load_by_name($username);

  if (!$account) {
    uibx_log('No user with the given username exist');
    return;
  }
  try {
    $w2u = new XTopic("username:$username");
  }
  catch (Exception $e) {
    if ($e->getCode() == 404) {
      uibx_log("Can't look up user $username in w2", "error");
      return;
    }
    throw $e;
  }

  $edit = array();
  if (isset($account->field_uib_slug['und'][0]['value'])) {
    if ($account->field_uib_slug['und'][0]['value'] != $w2u->slug) {
      $edit['field_uib_slug']['und'][0]['value'] = $w2u->slug;
    }
  }
  else {
    $edit['field_uib_slug']['und'][0]['value'] = $w2u->slug;
  }
  if (isset($account->field_uib_w2_id['und'][0]['value'])) {
    if ($account->field_uib_w2_id['und'][0]['value'] != $w2u->id) {
      $edit['field_uib_w2_id']['und'][0]['value'] = $w2u->id;
    }
  }
  else {
    $edit['field_uib_w2_id']['und'][0]['value'] = $w2u->id;
  }

  if (!empty($w2u->main_media)) {
    $file = xtopic_file($w2u->main_media, $account->uid);
    if ($file && (empty($account->picture) || $account->picture->fid != $file->fid)) {
      $file->status = FILE_STATUS_PERMANENT; // fake it since xtopic_file doesn't really load the file object
      $edit['picture'] = $file;
      file_usage_add($file, 'user', 'user', $account->uid);
    }
  }

  if (empty($edit)) {
    uibx_log("No change for $username <$account->mail>");
  }
  else {
    user_save($account, $edit);
    uibx_log("Updated fields for $username <$account->mail>");
  }

  // Update the path aliases if needed
  $slug = $w2u->slug;
  $source = 'user/' . $account->uid;
  foreach (array('nb' => 'personer', 'en' => 'persons') as $lang => $prefix) {
    $path_key = array(
      "source" => $source,
      "language" => $lang,
    );
    $alias = $prefix . '/' . $slug;
    $path = path_load($path_key);
    if (empty($path)) {
      $path = $path_key;
    }
    elseif ($path['alias'] == $alias) {
      continue; // no need up update the alias
    }
    $path['alias'] = $alias;
    path_save($path);
    uibx_log("Set $lang path alias for $username to $alias");
  }
}
