<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function uib_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

function uib_migrate__sync_w2_users($limit=100) {
  $offset = variable_get('uib_w2_user_offset', 0);

  $query = new EntityFieldQuery;
  $query = $query
    ->entityCondition('entity_type', 'user')
    ->fieldCondition('field_uib_user_domain', 'value', 'uib', '=')
    ->range($offset, $limit);
  $result = $query->execute();

  $count = 0;
  foreach (array_keys($result['user']) as $uid) {
    $account = user_load($uid);
    uib_migrate__sync_w2_user($account->name);
    $count++;
  }

  variable_set('uib_w2_user_offset', $count < $limit ? 0 : $offset + $count);
}


/**
 * Fetch information about users still maintained in w2.
 *
 * This currently includes the slug and user picture.
 * A side effect of fetching the slug is to maintain path
 * aliases compatible with w2.
 */

function uib_migrate__sync_w2_user($username) {
  $account = user_load_by_name($username);
  if (!$account) {
    uibx_log('No user with the given username exist');
    return;
  }
  try {
    $w2u = new XTopic("username:$username");
  }
  catch (Exception $e) {
    if ($e->getCode() == 404) {
      uibx_log("Can't look up user $username in w2", "error");
      return;
    }
    throw $e;
  }

  $edit = array();
  if (isset($account->field_uib_slug['und'][0]['value'])) {
    if ($account->field_uib_slug['und'][0]['value'] != $w2u->slug) {
      $edit['field_uib_slug']['und'][0]['value'] = $w2u->slug;
    }
  }
  else {
    $edit['field_uib_slug']['und'][0]['value'] = $w2u->slug;
  }
  if (isset($account->field_uib_w2_id['und'][0]['value'])) {
    if ($account->field_uib_w2_id['und'][0]['value'] != $w2u->id) {
      $edit['field_uib_w2_id']['und'][0]['value'] = $w2u->id;
    }
  }
  else {
    $edit['field_uib_w2_id']['und'][0]['value'] = $w2u->id;
  }

  if (!empty($w2u->main_media)) {
    if (!isset($account->picture->field_uib_w2_id['und'][0]['value']) || $account->picture->field_uib_w2_id['und'][0]['value'] != $w2u->main_media) {
      if (!empty($account->picture->fid)) {
        file_usage_delete($account->picture, 'user', 'user', $account->uid);
      }
      $file = xtopic_file($w2u->main_media, $account->uid, $account->language);
      if ($file && (empty($account->picture) || $account->picture->fid != $file->fid)) {
        $file->status = FILE_STATUS_PERMANENT;
        $edit['picture'] = $file;
        file_usage_add($file, 'user', 'user', $account->uid);
      }
    }
  }

  if (empty($edit)) {
    uibx_log("No change for $username <$account->mail>");
  }
  else {
    user_save($account, $edit);
    uibx_log("Updated fields for $username <$account->mail>");
  }

  // Update the path aliases if needed
  $slug = $w2u->slug;
  $source = 'user/' . $account->uid;
  foreach (array('nb' => 'personer', 'en' => 'persons') as $lang => $prefix) {
    $path_key = array(
      "source" => $source,
      "language" => $lang,
    );
    $alias = $prefix . '/' . $slug;
    $path = path_load($path_key);
    if (empty($path)) {
      $path = $path_key;
    }
    elseif ($path['alias'] == $alias) {
      continue; // no need up update the alias
    }
    $path['alias'] = $alias;
    path_save($path);
    uibx_log("Set $lang path alias for $username to $alias");
  }
}

/**
 * Fetch user
 * Fetches an existing w3 user uid
 *
 * @param  string $user UiB user name
 * @return integer      Drupal user uid
 */
function uib_migrate__get_user($user_name) {
  static $users = array();
  if (empty($user_name)) {
    return FALSE;
  }
  $return_value = FALSE;
  if (is_string($user_name)) {
    if (!empty($users[$user_name])) {
      $return_value = $users[$user_name];
    }
    else {
      if ($w3_user = user_load_by_name($user_name)) {
        $return_value = $w3_user->uid;
        $users[$user_name] = $w3_user->uid;
      }
    }
  }
  return $return_value;
}

/**
 * Fetch UiB user name from w2
 * @param  integer $w2_user_id  w2 user id
 * @return string               UiB user name
 */
function uib_migrate__get_user_name($w2_user_id) {
  static $users_w2 = array();
  if (empty($w2_user_id)) {
    return FALSE;
  }
  $return_value = FALSE;
  if (is_numeric($w2_user_id)) {
    if (!empty($users_w2[$w2_user_id])) {
      $return_value = $users_w2[$w2_user_id];
    }
    else {
      $w2_user = new XTopic($w2_user_id, TRUE, 'Author name lookup');
      if ($w2_user->{'uib-id'}) {
        $return_value = $w2_user->{'uib-id'};
        $users_w2[$w2_user_id] = $w2_user->{'uib-id'};
      }
    }
  }
  return $return_value;
}
