<?php

/**
 * @file
 * Implement hook_menu_breadcrumb_alter().
 */
function uib_breadcrumb_menu_breadcrumb_alter(&$active_trail, $item) {
  if (path_is_admin(current_path())) {
    return;
  }
  $current_area = uib_area__get_current();
  if (!$current_area) {
    return;
  }
  $uib_active_trail = array();
  $uib_active_trail[0] = array_shift($active_trail);
  $uib_active_trail[1] = array(
    'title' => $current_area->title,
    'href' => 'node/' . $current_area->nid,
    'link_path' => '',
    'localized_options' => array(),
    'type' => 0,
  );
  if (isset($item['page_arguments'][0]->type)) {
    switch ($item['page_arguments'][0]->type) {
      case 'uib_article':
        switch ($item['page_arguments'][0]->field_uib_article_type['und'][0]['value']) {
          case 'news':
            $uib_active_trail[] = array(
              'title' => t('News archive'),
              'href' => $uib_active_trail[1]['href'] . '/news-archive',
              'link_path' => '',
              'localized_options' => array(),
              'type' => 0,
            );
            $year = date('Y', $item['page_arguments'][0]->created);
            $month = date('F', $item['page_arguments'][0]->created);
            $datelink = date('Ym', $item['page_arguments'][0]->created);
            $uib_active_trail[] = array(
              'title' => t($month) . ' ' . $year,
              'href' => $uib_active_trail[1]['href'] . '/news-archive/' . $datelink,
              'link_path' => '',
              'localized_options' => array(),
              'type' => 0,
            );
            break;
          case 'infopage':
            if (count($active_trail) > 1) {
              $item = (__uib_get_parent_item(__uib_get_plid('node/' . arg(1), 'menu-area-' . $current_area->nid)));
              $uib_active_trail[] = array(
                'title' => $item['link_title'],
                'href' => '',
                'link_path' => $item['link_path'],
                'localized_options' => array('attributes' => array('class' => array('uib-remove-link'))),
                'type' => 0,
              );
            }
            else {
              $uib_crumbs = __uib_get_breadcrumb(arg(1), array(), $current_area->nid);
              if (count($uib_crumbs) > 0) {
                $uib_crumbs = array_reverse($uib_crumbs);
                $first_relation = $uib_crumbs[0];
                $plid = __uib_get_plid($first_relation['href'], 'menu-area-' . $current_area->nid);
                if($active_trail[0]['mlid'] != $plid) {
                  if($parent = __uib_get_parent_item($plid)) {
                    $uib_active_trail[] = array(
                      'title' => $parent['link_title'],
                      'href' => $parent['link_path'],
                      'link_path' => '',
                      'localized_options' => array('attributes' => array('class' => array('uib-remove-link'))),
                      'type' => 0,
                    );
                  }
                }
                foreach ($uib_crumbs as $key => $crumb) {
                  if (!in_array($crumb, $uib_active_trail)) {
                    $uib_active_trail[] = $crumb;
                  }
                  else {
                    break;
                  }
                }
              }
            }
            break;
          case 'event':
            $uib_active_trail[] = array(
              'title' => t('Calendar'),
              'href' => $uib_active_trail[1]['href'] . '/calendar',
              'link_path' => '',
              'localized_options' => array(),
              'type' => 0,
            );
            $date = explode('-', $item['page_arguments'][0]->field_uib_date['und'][0]['value']);
            $uib_active_trail[] = array(
              'title' => (string)$date[0],
              'href' => $uib_active_trail[1]['href'] . '/calendar/year?dateyear=' . $date[0],
              'link_path' => '',
              'localized_options' => array(),
              'type' => 0,
            );
            $uib_active_trail[] = array(
              'title' => t(date("F", mktime(0,0,0,$date[1],1,2013))),
              'href' => $uib_active_trail[1]['href'] . '/calendar?date=' . $date[0] . '-' . $date[1],
              'link_path' => '',
              'localized_options' => array(),
              'type' => 0,
            );
            break;
        }
        break;
      case 'uib_study':
        $study_type = $item['page_arguments'][0]->field_uib_study_type['und'][0]['value'];
        $uib_active_trail[2] = array(
          'title' => ($study_type == 'course') ? t('Course') : t('Studyprogramme'),
          'href' => ($study_type == 'course') ? 'course' : 'studyprogramme',
          'link_path' => '',
          'localized_options' => array(),
          'type' => 0,
        );
        if ($item['page_arguments'][0]->field_uib_study_type['und'][0]['value'] == 'specialization') {
          $parent_nid = $item['page_arguments'][0]->field_uib_study_part_of['und'][0]['target_id'];
          $parent = node_load($parent_nid);
          global $language;
          $lang = $language->language;
          $uib_active_trail[3] = array(
            'title' => $parent->field_uib_study_title[$lang][0]['value'],
            'href' => 'node/' . $parent_nid,
            'link_path' => '',
            'localized_options' => array(),
            'type' => 0,
          );
        }
        break;
    }
  }
  $active_trail = $uib_active_trail;
}

/**
 * Implement hook_page_alter()
 */
function uib_breadcrumb_page_alter(&$page) {
  if (arg(0) == 'taxonomy' && arg(1) == 'term' && is_numeric(arg(2))) {
    $home = t('Home');
    $breadcrumb = array();
    $breadcrumb[] = l($home, '<front>');
    $current_area = uib_area__get_current();
    if ($current_area)
      $breadcrumb[] = l($current_area->title, 'node/' . $current_area->nid);
    $parent_term = taxonomy_get_parents(arg(2));
    if ($parent_term) {
      $parent_term_keys = array_keys($parent_term);
      global $language;
      $lang = $language->language;
      $parent_term_title = $parent_term[$parent_term_keys[0]]->field_uib_term_title[$lang][0]['safe_value'];
      $breadcrumb[] = l($parent_term_title, 'taxonomy/term/' . $parent_term_keys[0]);
    }
    drupal_set_breadcrumb($breadcrumb);
  }
}

/**
 * Recursive function aiming to get the part of the breadcrumb consisting
 * of related content.
 *
 * @param int $nid
 * @param array $crumbs
 * @param node $current_area
 *
 * @return array
 */
function __uib_get_breadcrumb($nid, $crumbs=array(), $current_area) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'uib_article')
    ->fieldCondition('field_uib_relation', 'target_id', $nid, '=');
  $result = $query->execute();
  if (!empty($result['node'])) {
    $ids = array_keys($result['node']);
    $parents = entity_load('node', $ids);
    foreach ($parents as $parent) {
      if ($parent->field_uib_area['und'][0]['target_id'] == $current_area) {
        $item = array(
          'title' => $parent->title,
          'href' => 'node/' . $parent->nid,
          'link_path' => '',
          'localized_options' => array(),
          'type' => 0,
        );
        $crumbs[] = $item;
        $crumbs = __uib_get_breadcrumb($parent->nid, $crumbs, $current_area);
      }
    }
  }
  return $crumbs;
}

/**
 * Getting the parent link id for items in the specified menu.
 *
 * @param string $path
 * @param string $menu_name
 *
 * @return int
 */
function __uib_get_plid($path, $menu_name) {
  $plid = db_select('menu_links' , 'ml')
  ->condition('ml.link_path' , $path)
  ->condition('ml.menu_name',$menu_name)
  ->fields('ml' , array('plid'))
  ->execute()
  ->fetchField();
  return $plid;
}

/**
 * Getting a links parent item.
 *
 * @param int $mlid
 *
 * @return array
 */
function __uib_get_parent_item($mlid) {
  $result = db_select('menu_links', 'ml')
   ->condition('ml.mlid', $mlid)
   ->fields('ml', array('link_path', 'link_title'))
   ->execute()
   ->fetchAssoc();
  return $result;
}
