<?php
/**
* This is an example of how to setup a block filled with a field_collection item
* which is connected to a node (i.e. setup in the node's content type).
*
* The node contains the entity id for the field_collection item, and this is
* obtained (entity_object_load), made renderable (entity_view), and rendered.
* The entity node type is 'field_collection_item'
*/

/**
 * Implements hook_block_info().
 */

function xxx_block_info() {
  return array(
      'shortcuts' => array(
      'info' => t('Shortcut links block'),
      'status' => TRUE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */

function xxx_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'shortcuts':
      $entity_type = 'field_collection_item';
      $current_node = xxx__get_current(); // get current node object
      if (!empty($current_node->field_uib_link_section['und'][0]['value'])) {
        $field_collection = entity_object_load($current_node->field_uib_link_section['und'][0]['value'], $entity_type);
        if (!empty($field_collection)) {
          $block['subject'] = t("shortcuts");
          $block['content']["#markup"] = drupal_render(entity_view($entity_type, array($field_collection)));
        }
      }
    break;
  }
  return $block;
}
